-- this is base config

EUET_ONLOAD = 0;
EUET_ONCLICK = 1;
EUET_ONRCLICK = 2;
EUET_ONHYPERLINK = 3;
EUET_ONUPDATE = 4;
EUET_ONENTER = 5;
EUET_ONCLOSE = 6;

EUSER_EVENT_SELFUPGRADE = 100;
EUSER_EVENT_FIRSTENTERGAME = 101;
EUSER_EVENT_UPDATEEVENTINFO = 102;
EUSER_EVENT_LOADGMEVENTINFO = 103;